sudo: false
language: node_js
cache:
  yarn: true
  directories:
  - "${HOME}/.cache/yarn"
  - node_modules
notifications:
  email:
    on_failure: always
node_js:
- "node"

before_install:
- yarn config set progress=false
script: yarn lint

before_deploy:
  - .travis/setup-git.sh > /dev/null 2>&1
deploy:
  provider: script
  script: npm run semantic-release
  skip_cleanup: true
  on:
    branch: master
